// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDwPwPsP7HcQXKURZVslY5O0sR7EbEIqLA',
    appId: '1:583527128111:web:332ba334db0c93c132bada',
    messagingSenderId: '583527128111',
    projectId: 'kory-care',
    authDomain: 'kory-care.firebaseapp.com',
    storageBucket: 'kory-care.appspot.com',
    measurementId: 'G-B30GGBMPH3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyChy1LwrL26Dxfmaol8DBBItgcjiy0bn7k',
    appId: '1:583527128111:android:d5c1d4985b9d1dbf32bada',
    messagingSenderId: '583527128111',
    projectId: 'kory-care',
    storageBucket: 'kory-care.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCsDS62MSpOb2SavoP0mQKTxWEz9Nfm4ks',
    appId: '1:583527128111:ios:1c3fdddc3ba4326732bada',
    messagingSenderId: '583527128111',
    projectId: 'kory-care',
    storageBucket: 'kory-care.appspot.com',
    iosClientId: '583527128111-btbk2lvrnksc6j5cqlqs2sv5gp6jro6a.apps.googleusercontent.com',
    iosBundleId: 'com.example.groceryApp',
  );
}
